### ISSUE TITLE
Installation error in Ubuntu with cuda v10.0

### ISSUE THREAD

**Issue by gabocas** [pjmark/NIPET#2]
Dear Pawel,

I am trying to install niftypet using the command

pip install --no-binary :all: --verbose nipet

but I got the error attached in the log file, have you seen this error before?

[log_niftypet_installation.log](https://github.com/pjmark/NiftyPET/files/2502447/log_niftypet_installation.log)

Thanks in advance for your help.

Best,

Gabriel

**Comment by pjmark** [comment]
Hello Gabriel


Thanks for your message and sorry you got this problem.


From the log file it seems that either you don't have CUDA devices installed on your machine or they are not supported, i.e., the compute capability is below 3.5.


I have updated the software so that it says that it raises an exception if any of the above occurs.  You may want to try with the latest versions (nipet v.1.0.17, nimpa v.1.0.18) and see if you get the exception raised.  Also you may already know if you have the supported GPUs installed or not.


In case of computer cluster or HPC computers, the installation requires a little bit of manual setup--let me know if that's the case for you.


Many thanks

Pawel

________________________________

**Comment by gabocas** [comment]
Hi Pawel,

Thanks for your help. I have 2 GPUs with a compute capability of 6.1. I just realized that is better to use Cuda 9.1 instead of 10; however, after installing, it gets stuck into the 2% of the building process, without giving an error or doing something else in the background (log attached). I tried also to install NIMPA, but it also gets stuck in the 8% of the building process. Have you experienced something similar before?

[log_niftypet_installation2.log](https://github.com/pjmark/NiftyPET/files/2507012/log_niftypet_installation2.log)

Best,

Gabriel

**Comment by pjmark** [comment]
Hi Gabriel


That's very weird.


I'm happy to connect with you to sort it out.  Are you ssh'able or skype'able?


Best,

Pawel

________________________________

**Comment by gabocas** [comment]
Thanks for your kind offer. Unfortunately, I am only skype'able, because the machine I am using is in the intranet. When would you have some time? My skype id is gabriel.castrillon

Best,

Gabriel

**Comment by pjmark** [comment]
I replied to you on skype.  Let me know if you got the message.


Cheers,

Pawel

________________________________
